config/routes.rb
Rails.application.routes.draw do  
  #index route
  root 'home#home'
  
  #contact form routes
  get '/contact', to: 'contact#new'
  post '/contact', to: 'contact#create'

  #create new user routes
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  #login
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :favourites, only: [:index, :create, :destroy]

  get '/favourites', to: 'favourites#index'
  post '/favourites', to: 'favourites#create'

  resources :albums

  #songs to be nested ontop of albums, so songs is after albums in url
  resources :songs, :path => "/albums/:album_id/songs", :except => [:show, :edit, :update]

  #map contacts to contact, restricts to create and new
  resources :contacts, :path => "contact", only: [:create,:new]

  #maps user path to "register" allowing the user of /register routes above, restricts to create and new
  resources :users, :path => "register", only: [:create,:new] 

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/song.rb
class Song < ApplicationRecord
    validates :name, :artist, :year, presence: true

    has_and_belongs_to_many :albums

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  #blocks access to ALL songs routes if not logged by using the helper method in application controller created
  #redirects to root url if not logged in
  before_action :authorized, only: [:index, :edit, :new, :create, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    #album id going to be useful for selecting songs
    album = Album.find_by(id: params[:album_id])

    @songs = album.songs.all
  end

  # GET /songs/new
  def new
    album = Album.find_by(id: params[:album_id])
    @song = album.songs.new
  end

  # POST /songs
  # POST /songs.json
  def create
    #checks if logged in user owns the album, if so songs can be added. to stop random logged in users adding songs
    if(current_user.albums.find_by(id: params[:album_id]))
      album = Album.find_by(id: params[:album_id])

      @song = album.songs.create(song_params)

      respond_to do |format|
        if @song.save
          format.html { redirect_to songs_url, notice: I18n.t('songs.created') }
          format.json { render :show, status: :created, location: @song }
        else
          format.html { render :new }
          format.json { render json: @song.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_song_url, notice: I18n.t('songs.invalid-operation')
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    #if song belongs to current user logged in
    if(current_user.albums.find(@song.albums.ids))
      @song.destroy
      respond_to do |format|
        format.html { redirect_to albums_url, notice: I18n.t('songs.deleted') }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:name, :artist, :year)
    end


end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= simple_form_for @song do |form|%>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> <%= t('songs.errors') %>:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.input :name %>
  </div>

  <div class="field">
    <%= form.input :artist %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.date_select :year %>
  </div>

  <div class="actions">
    <%= form.button :submit, class:"btn btn-default btn-light" %>
  </div>
<% end %>

app/views/songs/index.html.erb
<div class="container">
  <div class="jumbotron">
  <p id="notice"><%= notice %></p>
  <h3><%= t('songs.title') %></h3>
  <%= link_to 'Add new Song', new_song_path, class:"btn btn-default" %>
    <div class="row">
      <% @songs.each do |song| %>

        <div style="margin-top: 30px;" class="col-1">
          <div class="thumbnail">
            <!-- <img src="..." alt="..."> -->
            <div class="caption">
              <h3 class="songName"><td><%= song.name %></td></h3>
              <td class="songArtist"><%= song.artist %></td>
              <td class="songYear"><%= song.year %></td>
              <p>
              
                <%= link_to 'Delete', song_path(song.id, song), method: :delete, class:"btn btn-danger" %>
              </p>
            </div>
          </div>
        </div>

      <% end %>
    </div>
    <%= link_to 'Back', albums_path, class:"btn btn-default" %>
  </div>
</div>  

<br>

app/views/songs/new.html.erb
<div class="container">
    <div class="jumbotron">
        <h3>New Song</h3>
        <p class="errorMessage"> <%= notice %> </p>
        <%= render 'form', song: @song %>

        <%= link_to 'Back', songs_path, class:"btn btn-default btn-light" %>
    </div>
</div>