config/routes.rb
Rails.application.routes.draw do  
  #index route
  root 'home#home'
  
  #contact form routes
  get '/contact', to: 'contact#new'
  post '/contact', to: 'contact#create'

  #create new user routes
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  #login
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :favourites, only: [:index, :create, :destroy]

  get '/favourites', to: 'favourites#index'
  post '/favourites', to: 'favourites#create'

  resources :albums

  #songs to be nested ontop of albums, so songs is after albums in url
  resources :songs, :path => "/albums/:album_id/songs", :except => [:show, :edit, :update]

  #map contacts to contact, restricts to create and new
  resources :contacts, :path => "contact", only: [:create,:new]

  #maps user path to "register" allowing the user of /register routes above, restricts to create and new
  resources :users, :path => "register", only: [:create,:new] 

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    #attribute used for dynamically displaying the favourite button
    attr_accessor :favourites
    validates :name, :description, presence: true

    has_and_belongs_to_many :users, as: :collectable
    has_and_belongs_to_many :songs, as: :collectable
    has_many :favourites


    

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  #blocks access to ALL albums routes if not logged by using the helper method in application controller created
  #redirects to root url if not logged in
  before_action :authorized, only: [:index, :edit, :new, :create, :update, :destroy]

  def index
    if(current_user) 
      @albums = current_user.albums.all
      @albums.each do |album|
        #if current user already has favourited this album then use this attribute to decide whether favourite button should be visible
        album.favourites = !Favourite.find_by(album_id: album.id, user_id: current_user.id)
      end
    end
    
  end

  def edit
  end

  # GET /albums/new
  def new
    @album = current_user.albums.new
  end

  def create
    #this creates an album belonging to the user logged in
    @album = current_user.albums.create(album_params)


    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_url, notice: I18n.t('albums.created')  }
        format.json { render :index, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #checks if the logged in user updating the album owns the album so not any random registered user can update it
    if(current_user.albums.find(@album.id))
      respond_to do |format|
        if @album.update(album_params)
          format.html { redirect_to albums_url, notice: I18n.t('albums.updated') }
          format.json { render :index, status: :ok, location: @album }
        else
          format.html { render :edit }
          format.json { render json: @album.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    #checks if user deleting the album owns the album so not any random registered user can delete it
    if(current_user.albums.find(@album.id))
      @favourite = Favourite.find_by(album_id: @album.id)


      #BELOW DELETES SONGS AND FAVOURITES BEFORE DELETING ALBUM FOR REFERENTIAL INTEGRITY

      #deletes songs from songs table for the given album id
      @song = Song.joins(:albums).select('songs.id').where('albums.id' => @album.id)
      @song.destroy_all

      #deletes album reference in favourites before deleting the album
      if @favourite
        @favourite.destroy
      end
      
      #deletes album from the table
      if @album.destroy 
        redirect_to albums_url, notice: I18n.t('albums.deleted') 
      else 
        redirect_to albums_url, notice: @album.errors
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:name, :description)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for @album do |form| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> <%= t('albums.errors') %>:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.input :name %>
  </div>

  <div class="field">
    <%= form.input :description %>
  </div>

  <div class="actions">
    <%= form.button :submit, class:"btn btn-default btn-light" %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<div class="container">
    <div class="jumbotron">
    <h3>Editing Album</h3>
    <%= render 'form', album: @album %>
    
    <%= link_to 'Back', albums_path, class: "btn btn-default" %>
    </div>
</div>

app/views/albums/index.html.erb
<div class="container">
  
  <div class="jumbotron">
  <p id="notice"><%= notice %></p>

  <% if @albums.empty? %>
  <h3><%= t('albums.empty') %></h3>

  <% else %>
  <h3><%= t('albums.title') %></h3>
  <br>

      <div class="row">
      <% @albums.each do |album| %>

        <div class="col-sm-6 col-md-4">
          <div class="thumbnail">
            <div class="caption">
              <h3 class="albumName"><%= album.name %></h3>
              <h4 class="albumDescription"><%= album.description %></h4>
              <p>
                <%= link_to 'View', songs_path(album), class: "btn btn-primary" %> 
                <% if album.favourites %>
                <%= link_to 'Favourite', favourites_path(:album_id => album.id), method: :post, class:"btn btn-default" %>
                <% end %>
                <%= link_to 'Edit', edit_album_path(album),class:"btn btn-default" %>
                <%= link_to 'Delete', album, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
              </p>
            </div>
          </div>
        </div>

      <% end %>
      </div>
  <% end %>


  <%= link_to 'New Album', new_album_path,class:"btn btn-default" %>

  </div>
</div>

app/views/albums/new.html.erb
<div class="container">
    <div class="jumbotron">
        <h3>New Album</h3>
        <%= render 'form', album: @album %>
        <%= link_to 'Back', albums_path, class:"btn btn-default btn-light" %>
    </div>
</div>