config/routes.rb
Rails.application.routes.draw do  
  #index route
  root 'home#home'
  
  #contact form routes
  get '/contact', to: 'contact#new'
  post '/contact', to: 'contact#create'

  #create new user routes
  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  #login
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'


  resources :favourites, only: [:index, :create, :destroy]

  get '/favourites', to: 'favourites#index'
  post '/favourites', to: 'favourites#create'

  resources :albums

  #songs to be nested ontop of albums, so songs is after albums in url
  resources :songs, :path => "/albums/:album_id/songs", :except => [:show, :edit, :update]

  #map contacts to contact, restricts to create and new
  resources :contacts, :path => "contact", only: [:create,:new]

  #maps user path to "register" allowing the user of /register routes above, restricts to create and new
  resources :users, :path => "register", only: [:create,:new] 

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title> <%= t('app_title') %> </title>



    <meta name="description" content="<%=t('app_description')%>">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'modernizr' %>
    <%= csrf_meta_tags %>

  </head>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div>
        <ul class="nav navbar-nav">
          <li id="homeLink" class="<%= 'active' if current_page?(root_path) %>"><a href="/">Home </a></li>
          <% if current_user %>
          <li class="<%= 'active' if current_page?('/albums') %>"><a href="<%= albums_path %>">Albums</a></li>
          <li class="<%= 'active' if current_page?('/favourites') %>"><a href="<%= favourites_path%>">Favourites </a></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !current_user  %>
          <li><a href="<%= login_path %>">Login</a></li>
          <li><a href="<%= users_path %>">Register</a></li>
          <li><a href="<%= contact_path %>">Contact</a></li>
          <% else %>
          <li><a href="<%= contact_path %>">Contact</a></li>
          <li><a href="<%= "/logout" %>">Logout</a></li>
          <% end %>
          
        </ul>
    
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <body>

  

    <%= yield %>

  </body>
</html>